helmDefaults:
  cleanupOnFail: false
  diffArgs:
    - "--suppress-secrets"
  syncArgs:
    - "--labels=app.kubernetes.io/managed-by=helmfile"
  wait: true
  historyMax: 3
  createNamespace: false

repositories:
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets
  - name: fossorial
    url: https://charts.fossorial.io
releases:
  - name: kubeseal
    namespace: kubeseal
    createNamespace: true
    chart: sealed-secrets/sealed-secrets
    version: 2.17.7
    values:
      - "./kubeseal/values.yaml"
  - name: pangolin
    namespace: pangolin
    createNamespace: true
    chart: fossorial/newt
    version: 1.1.0
    values:
      - "./pangolin/values.yaml"
    hooks:
      - events: ["presync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ./pangolin/credentials.yaml
  - name: metallb
    namespace: metallb
    createNamespace: true
    chart: metallb/metallb
    version: 0.15.2
    values:
      - "./metallb/values.yaml"
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: kubectl
        args:
          - apply
          - -f
          - ./metallb/address_pool.yaml