resources:
  - ./cilium
  - ./kubeseal/flux-ks.yaml
  - ./external-secrets/flux-ks.yaml
  - ./cert-manager/flux-ks.yaml
  - ./prometheus/flux-ks.yaml
  - ./grafana/flux-ks.yaml
  - ./proxmox-csi/flux-ks.yaml
  - ./pangolin/flux-ks.yaml
  - ./cnpg-system
  - ./reloader
  - ./metrics-server
