namespaces:
  - name: cert-manager
  - name: littlelink
  - name: reloader
  - name: kubeseal
  - name: proxmox-csi
  - name: external-secrets
  - name: pangolin
  - name: karakeep
  - name: glance
  - name: cnpg-system
  - name: postgres
  - name: blinko
  - name: monitoring
    labels:
      pod-security.kubernetes.io/enforce: privileged