namespaces:
  - name: cert-manager
  - name: littlelink
  - name: reloader
  - name: kubeseal
  - name: security
  - name: pangolin
  - name: karakeep
  - name: glance
  - name: cnpg-system
  - name: monitoring
    labels:
      pod-security.kubernetes.io/enforce: privileged