---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaContactPoint
metadata:
  name: slack
  namespace: monitoring
spec:
  type: slack
  editable: false
  instanceSelector:
    matchLabels:
      grafana.internal/instance: homelab
  settings:
    recipient: alerts
  valuesFrom:
    - targetPath: token
      valueFrom:
        secretKeyRef:
          name: grafana-slack-token
          key: token