---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: kubernetes
  namespace: monitoring
spec:
  resyncPeriod: 12h
  title: "Kubernetes"
  instanceSelector:
    matchLabels:
      grafana.internal/instance: "homelab"