---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    grafana.internal/instance: "homelab"
spec:
  disableDefaultSecurityContext: All
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
      oauth_allow_insecure_email_lookup: "true"
    auth.generic_oauth:
      enabled: "true"
      name: "Pocket ID"
      client_id: homelab-grafana
      client_secret: ${GF_OIDC_CLIENT_SECRET}
      scopes: "openid email profile"
      skip_org_role_sync: "true"
      auth_url: "${GF_AUTH_URL}/authorize"
      token_url: "${GF_AUTH_URL}/api/oidc/token"
      api_url: ""
    security:
      admin_user: "${GF_SECURITY_ADMIN_USER}"
      admin_password: secret
    news:
      news_feed_enabled: "false"
    server:
      root_url: "https://${GF_DOMAIN}/"
      enable_gzip: "true"
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
  service:
    metadata:
      annotations:
        io.cilium/lb-ipam-ips: 192.168.20.175
    spec:
      type: LoadBalancer
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              resources:
                requests:
                  cpu: 10m
                  memory: 200Mi
                limits:
                  memory: 500Mi
              readinessProbe:
                failureThreshold: 3
              env:
                - name: GF_SECURITY_ADMIN_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secrets
                      key: GF_SECURITY_ADMIN_USER
                - name: GF_DOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secrets
                      key: GF_DOMAIN
                - name: GF_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secrets
                      key: GF_AUTH_URL
                - name: GF_OIDC_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secrets
                      key: GF_OIDC_CLIENT_SECRET
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-secrets
                      key: GF_SECURITY_ADMIN_PASSWORD
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities: { drop: ["ALL"] }
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
          volumes:
            - name: grafana-data
              persistentVolumeClaim:
                claimName: grafana-pvc
      strategy:
        type: Recreate
  persistentVolumeClaim:
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: proxmox-csi-retain