---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
  namespace: kagent
spec:
  interval: 1h
  timeout: 5m
  maxHistory: 2
  chartRef:
    kind: OCIRepository
    name: kagent-crds
  install:
    crds: CreateReplace
  values:
    kmcp:
      enabled: true
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent
  namespace: kagent
spec:
  dependsOn:
    - name: kagent-crds
      namespace: kagent
  interval: 1h
  timeout: 5m
  maxHistory: 2
  chart:
    spec:
      chart: kagent
      version: 0.7.17
      sourceRef:
        kind: HelmRepository
        name: kagent-helm-repo
        namespace: kagent
      interval: 5m
  values:
    kmcp:
      enabled: true
    providers:
      default: anthropic
      anthropic:
        provider: Anthropic
        model: "claude-3-5-haiku-20241022"
        apiKeySecretRef: kagent-secrets
        apiKeySecretKey: ANTHROPIC_API_KEY
      openAI:
        provider: OpenAI
        model: "gpt-4.1-mini"
        apiKeySecretRef: kagent-secrets
        apiKeySecretKey: OPENAI_API_KEY
      gemini:
        provider: Gemini
        model: "gemini-2.0-flash-lite"
        apiKeySecretRef: kagent-secrets
        apiKeySecretKey: GEMINI_API_KEY
    ui:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 1Gi
    controller:
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 512Mi
    agents:
      k8s-agent:
        enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
      kgateway-agent:
        enabled: false
      promql-agent:
        enabled: false
      istio-agent:
        enabled: false
      observability-agent:
        enabled: false
      argo-rollouts-agent:
        enabled: false
      helm-agent:
        enabled: false
      cilium-policy-agent:
        enabled: false
      cilium-manager-agent:
        enabled: false
      cilium-debug-agent:
        enabled: false
    tools:
      grafana-mcp:
        enabled: false
      querydoc:
        enabled: false
