---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kagent-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: kagent-secrets
    creationPolicy: Owner
  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: "kagent-openai-secret"
    - secretKey: GEMINI_API_KEY
      remoteRef:
        key: "kagent-gemini-secret"
    - secretKey: ANTHROPIC_API_KEY
      remoteRef:
        key: "kagent-anthropic-secret"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-mcp-server
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: github-mcp-server
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_PERSONAL_ACCESS_TOKEN
      remoteRef:
        key: "kagent-gh-mcp-pat"