---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxmox-csi
  namespace: proxmox-csi
spec:
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  targetNamespace: proxmox-csi
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/proxmox-csi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false