---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
parameters:
  storage: local-lvm
  cache: writethrough
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-csi-retain
allowVolumeExpansion: true
parameters:
  storage: local-lvm
  cache: writethrough
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer