---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: renovate-pr-impact-agent
  namespace: kagent
spec:
  model: gpt-4.1-mini
  provider: OpenAI
  apiKeySecret: kagent-secrets
  apiKeySecretKey: OPENAI_API_KEY
---
apiVersion: kagent.dev/v1alpha2
kind: RemoteMCPServer
metadata:
  name: github-mcp-remote # Explore if we can self-host the server with `http` instead of `stdin` protocol
  namespace: kagent
spec:
  description: "GitHub MCP Server"
  url: https://api.githubcopilot.com/mcp/
  protocol: STREAMABLE_HTTP
  headersFrom:
    - name: Authorization
      valueFrom:
        type: Secret
        name: github-mcp-server
        key: GITHUB_PERSONAL_ACCESS_TOKEN
  timeout: 5s
  terminateOnClose: true
