---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  targetNamespace: cert-manager
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-configs
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  targetNamespace: cert-manager
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/cert-manager/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false