---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-cred
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: newt-cred
    creationPolicy: Owner
  data:
    - secretKey: NEWT_ID
      remoteRef:
        key: "homelab-newt-id"
    - secretKey: NEWT_SECRET
      remoteRef:
        key: "homelab-newt-secret"
    - secretKey: PANGOLIN_ENDPOINT
      remoteRef:
        key: "homelab-pangolin-endpoint"