apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newt
  namespace: pangolin
spec:
  interval: 1h
  chart:
    spec:
      chart: newt
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: pangolin
        namespace: flux-system
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    newtInstances:
      - name: homelab
        enabled: true
        service:
          annotations:
            io.cilium/lb-ipam-ips: 192.168.20.170
        auth:
          existingSecretName: newt-cred
          keys:
            endpointKey: PANGOLIN_ENDPOINT
            idKey: NEWT_ID
            secretKey: NEWT_SECRET