theme:
  disable-picker: true
  background-color: 216 19 11
  contrast-multiplier: 1.1
  primary-color: 210 100 67
  positive-color: 132 59 37
  negative-color: 3 90 63
branding:
  custom-footer: |
    <p>Kavin Â© 2025</a></p>
  logo-url: https://avatars.githubusercontent.com/u/62742678?v=4
  favicon-url: https://avatars.githubusercontent.com/u/62742678?v=4
  app-name: "Mission Control"
  app-background-color: "#151519"
pages:
  - name: Cockpit
    hide-desktop-navigation: false
    head-widgets:
      - type: split-column
        widgets:
          - type: server-stats
            hide-header: true
            servers:
              - type: remote
                name: Rengoku (VPS)
                url: http://${RENGOKU_VPS_IP}:27973
                token: ${RENGOKU_GLANCE_AGENT_TOKEN}
                hide-mountpoints-by-default: true
                mountpoints:
                  "/":
                    hide: false
          - type: server-stats
            hide-header: true
            servers:
              - type: local
                name: Tenzen
                hide-mountpoints-by-default: true
                mountpoints:
                  "/":
                    hide: false
              - type: remote
                name: Tokito (Pi 3B+)
                url: http://glance-agent.glance.svc.cluster.local:27973
                hide-mountpoints-by-default: true
                mountpoints:
                  "/":
                    hide: false
    columns:
      - size: small
        widgets:
          - type: to-do
          - type: dns-stats
            service: adguard
            url: ${ADGUARD_HOME_URL}
            username: ${ADGUARD_HOME_USERNAME}
            password: ${ADGUARD_HOME_PASSWORD}
          - type: markets
            markets:
              - symbol: ^NSEI
                name: Nifty 50
                chart-link: https://www.tradingview.com/chart/?symbol=NIFTY
              - symbol: GOLDBEES.BO
                name: ETF Gold BeES
              - symbol: SILVERBEES.NS
                name: Silver ETF
              - symbol: OKTA
                name: Okta
                chart-link: https://www.tradingview.com/chart/?symbol=OKTA
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                symbol-link: https://www.google.com/search?tbm=nws&q=apple
                name: Apple
      - size: full
        widgets:
          - type: monitor
            cache: 1m
            title: HomeLab Services
            sites:
              - title: AdGuard Home
                same-tab: true
                timeout: 5s
                url: ${ADGUARD_HOME_URL}
                icon: di:adguard-home.png
              - title: Bezel
                same-tab: true
                timeout: 5s
                url: ${BEZEL_MONITOR_URL}
                icon: si:bricks
              - title: Karakeep
                same-tab: true
                timeout: 5s
                icon: di:karakeep.png
                url: ${KARAKEEP_MONITOR_URL}
              - title: Littlelink
                same-tab: true
                timeout: 5s
                icon: di:littlelink-custom.png
                url: ${LINKS_URL}
          - type: group
            widgets:
              - type: reddit
                subreddit: kubernetes
                collapse-after: 6
              - type: reddit
                subreddit: selfhosted
                collapse-after: 6
              - type: reddit
                subreddit: homelabindia
                collapse-after: 6
          - type: videos
            channels:
              - UC9x0AN7BWHpCDHSm9NiJFJQ
              - UCFe9-V_rN9nLqVNiI8Yof3w
              - UCOk-gHyjcWZNj3Br4oxwh0A
              - UCXuqSBlHAE6Xw-yeJA0Tunw
      - size: small
        widgets:
          - type: search
            search-engine: google
            target: _self
          - type: clock
            time-format: 24h
            date-format: d MMMM yyyy
            show-seconds: true
            show-timezone: true
            timezone: Asia/Kolkata
          - type: weather
            location: Pollachi
            units: metric
            hour-format: 12h
          - type: calendar
            first-day-of-week: monday
