---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-server
  namespace: security
spec:
  commonName: bitwarden-sdk-server
  dnsNames:
    - bitwarden-sdk-server
    - bitwarden-sdk-server.security
    - bitwarden-sdk-server.security.svc
  duration: 8760h0m0s
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: self-signed
  secretName: bitwarden-tls-certs
