apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc:9998
      auth:
        secretRef:
          credentials:
            name: bws-access-token
            namespace: external-secrets
            key: ACCESS_TOKEN
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: external-secrets
        key: ca.crt
      organizationID: 93068d9b-a34e-4eb8-80e9-b3bb00f2c6ae
      projectID: 2fe2c5ed-e055-44a6-89a6-b3bb00fb55b1