services:
  glance-agent:
    container_name: glance-agent
    image: glanceapp/agent
    volumes:
      - /storage:/storage:ro
    environment:
      TOKEN: ${GLANCE_AGENT_TOKEN}
    ports:
      - 27973:27973