services:
  glance-agent:
    container_name: glance-agent
    image: glanceapp/agent
    volumes:
      - /storage:/storage:ro
    environment:
      TOKEN: <insert-token-here>
    ports:
      - 27973:27973