namespace: adguard

labels:
  - pairs:
      homelab.imkavin.dev/app: adguardhome
    includeSelectors: false

resources:
  - config.yaml
  - credentials.yaml
  - volumes.yaml
  - deployment.yaml
  - service.yaml