newtInstances:
  - name: homelab
    enabled: true
    service:
      annotations:
        metallb.io/loadBalancerIPs: 192.168.0.121
    auth:
      existingSecretName: newt-cred
      keys:
        endpointKey: PANGOLIN_ENDPOINT
        idKey: NEWT_ID
        secretKey: NEWT_SECRET