---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: flux-alert-slack
  namespace: flux-system
spec:
  type: slack
  channel: alerts
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: fluxcd-slack-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: helm-errors
  namespace: flux-system
spec:
  eventMetadata:
    summary: Flux Helm Errors
  providerRef:
    name: flux-alert-slack
  eventSeverity: error
  eventSources:
    - kind: HelmRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: kustomization-errors
  namespace: flux-system
spec:
  eventMetadata:
    summary: Flux Kustomize Errors
  providerRef:
    name: flux-alert-slack
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: "*"