---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: karakeep-secrets
    creationPolicy: Owner
  data:
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: "karakeep-meili-key"
    - secretKey: NEXT_PUBLIC_SECRET
      remoteRef:
        key: "karakeep-nextpublic-secret"
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: "karakeep-nextauth-secret"
    - secretKey: NEXTAUTH_URL
      remoteRef:
        key: "karakeep-nextauth-url"