---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blinko
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blinko
  template:
    metadata:
      labels:
        app: blinko
    spec:
      containers:
        - name: web
          image: blinkospace/blinko:1.8.3
          ports:
            - containerPort: 1111
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXTAUTH_URL
              valueFrom:
                secretKeyRef:
                  name: blinko-secrets
                  key: DOMAIN
            - name: NEXT_PUBLIC_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: blinko-secrets
                  key: NEXTAUTH_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: blinko-secrets
                  key: NEXTAUTH_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: blinko-secrets
                  key: DATABASE_URL
          resources:
            requests:
              cpu: 50m
              memory: 150Mi
            limits:
              memory: 250Mi
          volumeMounts:
            - name: blinko-data
              mountPath: /app/.blinko
      volumes:
        - name: blinko-data
          persistentVolumeClaim:
            claimName: blinko-data