---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: blinko-secrets
  namespace: blinko
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: "blinko-next-auth-secret"
    - secretKey: DATABASE_URL
      remoteRef:
        key: "blinko-database-url"
    - secretKey: DOMAIN
      remoteRef:
        key: "blinko-domain"
    - secretKey: NEXTAUTH_URL
      remoteRef:
        key: "blinko-next-auth-url"