---
apiVersion: v1
kind: Service
metadata:
  name: blinko
  annotations:
    io.cilium/lb-ipam-ips: 192.168.20.155
spec:
  selector:
    app: blinko
  ports:
    - protocol: TCP
      port: 1111
      targetPort: 1111
  type: LoadBalancer