apiVersion: v1
kind: Service
metadata:
  annotations:
    io.cilium/lb-ipam-ips: 192.168.20.151
  labels:
    io.kompose.service: littlelink-server
  name: littlelink-server
  namespace: littlelink
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 3000
  selector:
    app: littlelink-server
