---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: glance
    app.kubernetes.io/instance: glance
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glance
      app.kubernetes.io/instance: glance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glance
        app.kubernetes.io/instance: glance
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: glance
          image: "docker.io/glanceapp/glance:latest"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              memory: 100Mi
          env:
            - name: LINKS_URL
              value: https://links.imkavin.dev
            - name: KARAKEEP_MONITOR_URL
              value: http://web.karakeep.svc.cluster.local:3000
            - name: PROXMOXVE_URL
              value: "192.168.20.110:8006"
            - name: PROXMOXVE_KEY
              valueFrom:
                secretKeyRef:
                  name: pmx-api-ro-token
                  key: token
            - name: VPS_IP
              valueFrom:
                secretKeyRef:
                  key: address
                  name: vps-ip-address
            - name: VPS_GLANCE_TOKEN
              valueFrom:
                secretKeyRef:
                  key: token
                  name: vps-glance-token
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: glance-config
              mountPath: /app/config/glance.yml
              subPath: glance.yml
      volumes:
        - name: glance-config
          configMap:
            name: glance-config
---
apiVersion: v1
kind: Service
metadata:
  name: glance
  labels:
    app.kubernetes.io/name: glance
    app.kubernetes.io/instance: glance
  annotations:
    io.cilium/lb-ipam-ips: 192.168.20.160
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: glance
    app.kubernetes.io/instance: glance
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
