---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pmx-api-ro-token
  namespace: glance
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: "pmx-api-ro-user-token"
