---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus
  namespace: monitoring
spec:
  targetNamespace: monitoring
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/prometheus/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-configs
  namespace: monitoring
spec:
  dependsOn:
    - name: prometheus
    - name: external-secrets
      namespace: external-secrets
  targetNamespace: monitoring
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/prometheus/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false