---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubeseal
  namespace: kubeseal
spec:
  targetNamespace: kubeseal
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/kubeseal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false