---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-configs
  namespace: external-secrets
spec:
  dependsOn:
    - name: external-secrets
  targetNamespace: external-secrets
  interval: 30m
  timeout: 5m
  path: ./kubernetes/system/external-secrets/configs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false