---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bws-access-token
  namespace: security
spec:
  encryptedData:
    ACCESS_TOKEN: AgCJkWoqnbTK6Ye4dWg3FYIohdsgZf2oA49BopxZxjRjjpRQ51Wqtg/bA762Iua26i2E04xCFzQvYRzUu5iH9W6n+kmeqEsPs11gpx2LudMjbBUJKenGTi924mpRp26ec71mm7B98ioy5pEqlPsETojRTtQhqASoLFOLZ/leq5AmEpnpw+VJOUZGL939dYs3ij8vqZY5mRBB6vx5IEm31x/4mFaQh8vc4rTCezC3OPdsekUzWxLAFmQL7Uw727jb22w2Qi0hGxKUxsuOAzPp/iodxKe2yrVVCC6T7xxz8AC654QvHx0ogGbKa4kZMFGhE9ejriE1HdsF8Qec4UrmH7HLYcDIS6v3BvOQ/y4Y1CkFiNFo6E5fy9IGbk03NZPLDSMADUoUy1p8OKuKaDYKV9OKn1/41qD65nxquVCdtRtbvEkiTNjF8icJDt29h5cWT8TOseZutylKnmP8un3Gg60hGSdcEvgj2z1OXxfASn8Ddj+N6fb4SXC09grA9gk0h6G7XWQDntu1k12o/x2/qxenG5WlxiFNigmdhVJqVjorS6dg7pwSeL3imLlhnN7Bwan2pl67W0gvFp3NpGgXQE2hT49ySpPapCQY7467Ygn0QzAaFKC93/yieUag2z81nJsbE+BN/fSCwTg5P/Rei8kN5XciycWsZMkC9TNUnXPdMkHv7CP/3FsrN2LTuQ9ZpE1XV88crS4GWkZzYfwJfMMtlrN2YhlJxZBcmXzvENuyefD2cr8JGoyLELA66EhsYBTG8K+CMzhcaOLIFCM56OKkDviIVQ9g/0oI2tchP9LtFXJhkcQHMkhUvVegWXK0
  template:
    metadata:
      name: bws-access-token
      namespace: security
