---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bws-access-token
  namespace: security
spec:
  encryptedData:
    ACCESS_TOKEN: AgAV/GbkrBPKV7oOP1/8LBsRjPlvs7Q9YLt4A7fuX/Q87LgaAT7TfNRJhufwjFyo8WX7Gbgm/BIJs+xwtlFhjHObVVCWtx4qGibWfn4HQ3f/lLHkIdJjXjeChkc2sTuj1aKTcqlzdUazw6vAVt42ZFcc9VIkaAElmqCKa+f6lq4O9PR1npakbdgFMELQ3oWUwr7Cgq4X4cXQZkx3EMcjrSAMODoHKkP6W2cUzNZU7Xashir268lqgjej16kcl+sI9LORdfwWmeKRQ7t9epjAMuFDIPUlIY0Hy4Rc5efFglqUfMyWj8GH7y1i3Z6u2IupV3fDjZXqskGQums0d61tbd9NNXNz+kroWIFaTnw7eqjmcXjPZtr4i+znuDvU5mpKqbtNXye/TSybswmWMNRWN4y75usq2BoWRYUSrHWySRnS6ev1Glo9KEIBM7/AvovUDGhuejbxqWBsv3JQTcpu5S33p5OcLZr3SIStMnpCzLK9aMnFpKWqGeyXxE7+6U0x/SQaG7gBU1SLVfhaXBJRWriT+esxtCczOW0lRX01CvhZPO8a1sxBXff1K5RcM8J9sUrGL7n0bX9XszXgeYXJPOSPxB9GbLi0h+k/0ngHc9XaU2JjxyD0sgsQhXGrBJenCNCVt6+FEE5lQvCRKTkSqrceNZnhaEoVhyoI8jjHmm/MIVUVE7o79Dg7E1xr0OKbHqbpLmdFfnWM5iBS/8sQeyx+WFBlU/YbR22yiGipqlqM2wTFbskS1ASPnKWbbB6qXgjYU/VX/2Zqx1oEOPs3edOt5HpoNzS8DUUOIJ/s5a1MHjyXLmLl4NELuNkNtUAoHWo=
  template:
    metadata:
      name: bws-access-token
      namespace: security
