---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bws-access-token
  namespace: external-secrets
spec:
  encryptedData:
    ACCESS_TOKEN: AgBco7xXBOPS1Iv/o05RSE93F4CQjYUryCXZ7E0AoIeTfXhiND1DkoElX3/Lt1RNTzgaYyp8ys7L3UK1+dDq2zm+d0kO6ZYuwpJJgDS59yMPSxHA7Uy/EWjT8HgnYIKV4+lMRaYtbHS0uARUGgqE9x/C69B0L1hhe94EOTVExwtIZwIZxnvv3Xc+CLSFbDLLYEBTMZGIvCOLz7IlsZ9+WzZl0XQHnQrzALlOklgLDHC0HuthTMgVMWBh/uHLIGWnLtkjw4FwifKRX/ryy+Q29lqW3AtyLx2qITf/ZaQY1wvPQDOcR/ffLlMV6Ly/2qkfN9kKUuup+EU6Exh2Y1smTrVfjtN2Fp0E9eH5icToqZXJZBhxxa2JZDnpa/MV1UXiGSSifPnMxNHMHX/qIgjoVl4lK4DyP7KGDe3pRI4pByut20UwPeCOGXaIKYr+DAK+jNsDCEce4hZphzS62qi++08nozznJBuqYiJJvEztYmptli8fCr2FjObeiz9zJBDENKFbJ3i1BcRCHG6AohgWdBottYqBhIgJboDZTb8V3JTSKN6hrwPwAh3aYIjUCNPvj9CFvI+JgC8wWzIkBWmpszCfE6Ai2c+wQXTPUnp11MiaPs3T39DcZKhKQI6g6LZs0kp4EC47XVG+vgu1lgSEED5vm2v2RH27HwC06SPOHgeGq50LmQH3IeEURDsjQ3Iwa4m9DqaICz+MRF2aUf4xWjbwMeAH+F2NoR4IMovVP3Q77vjvKv2YDG3iPmyi3Ou214AfikEqN/moNDgo+Dvy6J0VzTLrdwGRvr91suRe+9VQ1ELNoJYCo90i3rcGGXFl
  template:
    metadata:
      name: bws-access-token
      namespace: external-secrets
